### ISSUE TITLE
No source code available

### ISSUE THREAD

**Issue by vkael** [Readix1/dofusOverlay_OpenSource#1]
Only .gif and images are available for this project.

Is source code ready for deployment and everyday usage ?

**Comment by Readix1** [comment]
yes but I prefere to get a positive response from ankama before publish it.
Organizer should be the solution for you

**Comment by Readix1** [comment]
Voila le code

**Comment by vkael** [comment]
Thanks for the feedback @Readix1, I'll have a look !
