### ISSUE TITLE
Ne fonctionne pas sur dofus 3.0

### ISSUE THREAD

**Issue by CallMeAl3x** [Readix1/dofusOverlay_OpenSource#3]
Je crois que tout est dans le titre :) Je voudrais savoir si y'a une possibilitée que le projet évolue pour s'adapter à dofus 3.0?

**Comment by Readix1** [comment]
Salut
Il y a une branche unity
Tu aurais un overlay similaire à dofus guide mais avec des corrections de bug et des options supplémentaires.
Je déconseille d'utiliser la macro clic + switch parce que je n'ai pas demandé la confirmation à ankama

**Comment by Readix1** [comment]
Ah je n'ai pas encore fait de version .exe
Je pourrai te faire une version demain

**Comment by CallMeAl3x** [comment]
> Ah je n'ai pas encore fait de version .exe Je pourrai te faire une version demain

Parfait merci !! 

Ton application est super au passage

**Comment by Readix1** [comment]
L'ancienne version ?
Je ne suis pas sur d'avoir mis la possibilité de mettre l'ancien visuel

Cool, ravis que ça te plaise

**Comment by CallMeAl3x** [comment]
> L'ancienne version ? Je ne suis pas sur d'avoir mis la possibilité de mettre l'ancien visuel
> 
> Cool, ravis que ça te plaise

Oui l'ancienne version, j'ai pas testé la nouvelle vu que j'y connais rien en python et comment faire une version .exe!

**Comment by Readix1** [comment]
Je te fais ça demain alors
En attendant tu peux utiliser https://dofusguide.fr/accueil
Leur organiser à le même visuel

**Comment by Readix1** [comment]
Salut, 
j'ai ajouté une release 3.0. Tu pourras télécharger en .zip
j'ai ajouté un raccourci pour exécuter le .exe avec un dofus pourpre comme illustration. (il est probable qu'il soit nécessaire de modifier les propriétés du raccourci en allant dans propriété -> raccourci -> cible (changer le "dofusOverlay.exe" en "C:\path\dofusOverlay.exe" et Démarrer dans (C:\path).
